# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-16 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('N', 'No Especificada'), ('S', 'Secuela'), ('P', 'Precuela'), ('H', 'Historia Paralela'), ('O', 'Ovas'), ('M', 'Pelicula'), ('A', 'Alternativo'), ('X', 'Principal')], default='N', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Series Relaciones',
                'verbose_name': 'Series Relacion',
                'db_table': 'SeriesRelacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, verbose_name='Codigo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('rank', models.TextField(choices=[('1', 'Mala'), ('2', 'Regular'), ('3', 'Buena'), ('4', 'Muy Buena'), ('5', 'Excelente')], default='2', max_length='1', verbose_name='Calificacion')),
                ('image', models.ImageField(default='media/uploads/default_image.png', upload_to='media/uploads', verbose_name='Portada')),
                ('chapters', models.IntegerField(verbose_name='Numero de Capitulos')),
                ('status', models.CharField(choices=[('P', 'Proximamente'), ('A', 'En Emision'), ('F', 'Finalizada')], max_length=1, verbose_name='Estado')),
                ('gender', models.CharField(max_length=150, verbose_name='Genero')),
                ('in_disk', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Almacena Localmente')),
                ('complete', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Completa')),
                ('ubication', models.CharField(default='/', max_length=255, verbose_name='Ubicacion')),
                ('observations', models.TextField(default='', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'verbose_name': 'Serie',
                'db_table': 'Series',
                'ordering': ['code', 'name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.CharField(default='http://', max_length=150, verbose_name='url')),
                ('url_format', models.CharField(default='http://', max_length=150, verbose_name='formato')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Serie')),
            ],
            options={
                'verbose_name_plural': 'Servidores',
                'verbose_name': 'Servidor',
                'db_table': 'Servidores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='relacionseries',
            name='serie_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_a', to='Main.Serie'),
        ),
        migrations.AddField(
            model_name='relacionseries',
            name='serie_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_b', to='Main.Serie'),
        ),
    ]
